---
version: '3.8'
services:
  sci_crawler: 
    build: ./Scrapy/raw_material
    networks:
      - dev

  news_crawler:
    build: ./Scrapy/news
    networks:
      - dev

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev

volumes:
  db:

networks:
  dev: 
    external: true